### ISSUE TITLE
Cannot unmount - program closing (Mac OS X El Capitan)

### ISSUE THREAD

**Issue by zeitchef** [thefanclub/dd-utility#2]
I get an Applescript error message every time.

**Comment by thefanclub** [comment]
Please be more specific. What error ?

**Comment by thefanclub** [comment]
dd Utility Version 1.6 supports Mac OS X El Capitan

**Comment by zeitchef** [comment]
I get an Applescript notification with the above: Cannot unmount - program closing

**Comment by thefanclub** [comment]
This happens if your memory stick or USB is in use and dd Utility cannot unmount the media. Make sure you use version 1.6. Try eject and re-insert, then run program again.

In some cases it helps to format your Memory card / USB Stick before using dd utility.

**Comment by burtyish** [comment]
Upgrading from v1.5 to 1.6 solved this for me.
