### ISSUE TITLE
App does not recognice disks which are not (fully) mounted

### ISSUE THREAD

**Issue by tigerduck42** [thefanclub/dd-utility#3]
Hi,
non mountable disks can't be selected. e.g. Disks with Linux partitions /dev/disk1

<pre>/dev/disk0
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            499.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
<b>/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *7.9 GB     disk1
   1:                      Linux                         15.7 MB    disk1s1
   2:                      Linux                         7.9 GB     disk1s2</b>
/dev/disk2
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS BigDisk                 999.9 GB   disk2s2
</pre>

Kindest regards
Martin

**Comment by thefanclub** [comment]
Hi Martin,

Yes, unmounted disks could not be used, but is possible. Added feature in mac OS version 1.7  

Regards
Christiaan

**Comment by tigerduck42** [comment]
Thanks for your fast reply.
It works if I use my external card reader but not if I use the internal one. But that's fine for me.
Kindest regards
Martin

**Comment by thefanclub** [comment]
Try version 1.8. Used a different approach. Should work with internal reader as well. 
Regards
Christiaan

**Comment by tigerduck42** [comment]
Awesome, working now with internal card reader as well.
Kindest regards
Martin
