### ISSUE TITLE
Restore in progress... seems to hang

### ISSUE THREAD

**Issue by berthelemy** [thefanclub/dd-utility#6]
Hi there,
I'm restoring an image to an SD card, and tracking activity using the "top" command.

The files appear to have copied across, and created two partitions, which I can access.
top is no longer showing gzip or dd in its list of active processes.

Doing ps aux | grep dd returns a load of lines with "a**dd**ress", plus the following:

uuidd     3987  0.0  0.0  29892     0 ?        Ss    2017   0:00 /usr/sbin/uuidd --socket-activation
root      5336  0.0  0.0  42900  2208 ?        Ss    2017   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
markber+ 13191  0.0  0.1 635928 29416 ?        Sl   09:40   0:02 gksudo /bin/bash /opt/thefanclub/ddutility/ddutility.sh
root     13196  0.0  0.0  63072  4160 ?        Ss   09:40   0:00 /usr/bin/sudo -H -S -p GNOME_SUDO_PASS -u root -- /bin/bash /opt/thefanclub/ddutility/ddutility.sh
root     13206  0.0  0.0  14344  3036 ?        S    09:40   0:00 /bin/bash /opt/thefanclub/ddutility/ddutility.sh
root     13507  1.3  0.0  10124  2560 ?        S    09:41   0:37 dd of=/dev/sdc bs=1M
root     13508  0.0  0.0  14380  2604 ?        S    09:41   0:00 /bin/bash /opt/thefanclub/ddutility/ddutility.sh
root     13509  0.0  0.2 388004 39472 ?        Sl   09:41   0:00 zenity --progress --title=dd Utility - 31.9 GB Volume Restore --width=400 --text=Restore in progress... --ok-label=Done --no-cancel --auto-close
markber+ 19564  0.0  0.0  15964   948 pts/6    S+   10:27   0:00 grep --color=auto dd

So, it looks like the DD Utility has finished, but the progress bar is still showing zero progress.

How can I tell whether it's finished?

I'm working on Ubuntu 16.04

Thanks,

Mark

**Comment by tioguda** [comment]
> So, it looks like the DD Utility has finished, but the progress bar is still showing zero progress.

I solved this error by installing the "lsof" package in my Manjaro Linux.
