### ISSUE TITLE
Buckup image without empty space. Is it possible?

### ISSUE THREAD

**Issue by romankh3** [thefanclub/dd-utility#8]
Hello developers!
I tried to use command `dd` in the terminal and found that it makes the backup size max of the microSD size, even it has 5% of the full size.

Does `dd-utility` help me with it?

Best regards, 
Roman.

**Comment by thefanclub** [comment]
Hi
Yes - if you select to compress the image during backup. This will greatly reduce the size if there is lots of empty space in the image file.
Regards
